### ISSUE TITLE
Route [stormpath.idSiteResponse] not defined.

### ISSUE THREAD

**Issue by georgeboot** [stormpath/stormpath-laravel#22]
Does this package not yet support the idSite?

Read all the way through the docs but could not find anything that solves this.

**Comment by bretterer** [comment]
Hello @georgeboot,  It appears that the files for ID Site did not make it into 0.1.0 release.  I will make a pull request ASAP to resolve this issue.

-Brian

**Comment by bretterer** [comment]
ID Site will fully be supported in our next release coming soon... You can use the develop branch until the release happens
