### ISSUE TITLE
Uncaught Exception on invalid ID Site Model

### ISSUE THREAD

**Issue by bretterer** [stormpath/stormpath-laravel#38]
When creating a new application, the ID Site Model is not generated and will return null instead of the URL in the API request for the application.  This was causing an error in the integration that we were not handling.  We need to catch this exception in the laravel integration to display useful information here.

**Comment by cmgmyr** [comment]
:+1: I'm getting this too

**Comment by bretterer** [comment]
@cmgmyr thank you for confirming this.   I will be working on this bug today

**Comment by bretterer** [comment]
Until an update for this is made, to resolve the issue, Click on ID Site from inside the Stormpath UI Dashboard and it will resolve itself.  This causes the ID Site Model to be created.

**Comment by bretterer** [comment]
Fixed and will be released in 0.4.0
