### ISSUE TITLE
Package not compatible with new Laravel 5.2.30 app

### ISSUE THREAD

**Issue by mapsi** [stormpath/stormpath-laravel#46]
Hello there,

I'm currently evaluating auth/sso solutions and I tried to follow the guide for a prototype app, but when I do a `composer require stormpath/laravel` on a new Laravel 5.2.30 app, I get a

```
Your requirements could not be resolved to an installable set of packages.
```

Could you please shed some light?

Many thanks,
Angel

**Comment by bretterer** [comment]
@mapsi 

So sorry for the late response here.  

There is a known issue with using `composer require stormpath/laravel` from the command line.  To install the laravel package, you will need to edit the `composer.json` file and add `"stormpath/laravel": "^0.4"` to your `require` section.  After doing this and saving the file, run `composer update` from the command line. 

You can get more information on what is going on from issue #17  which links to the information from Composer on what is going on.

-Brian
