### ISSUE TITLE
this package is not working on Laravel 5.2.x

### ISSUE THREAD

**Issue by nurettintopal** [stormpath/stormpath-laravel#47]
when I add "stormpath/laravel": "^0.4" to composer.json file, run ''composer update" from my command line, I have received Runtime Exception.

I think so, this package not compatible with new Laravel 5.2.x

![screen shot 2016-05-02 at 16 42 48](https://cloud.githubusercontent.com/assets/1067132/14955783/f9db52ce-1084-11e6-8908-292270828af2.png)

**Comment by bretterer** [comment]
@nurettintopal 

I cant seem to re-produce this error.  Can you give me step by step what you did here so I can try to troubleshoot this. 

Here are the steps that I did.
1. Run `laravel new test`
2. Open `composer.json`
3. Add `"stormpath/laravel": "^0.4"` to `require` section and save file
4. Run `composer update`
5. Open `config/app.php`
6. Add `Stormpath\Laravel\Support\StormpathLaravelServiceProvider::class,` at the bottom of the `providers` section and save
7. Run `php artisan optimize`

This seems to work on my end.  If you have any error logs that is more than what shows in terminal, Please send those along and I can take a look at them.

-Brian

**Comment by nurettintopal** [comment]
@bretterer 

in my project
- laravel/framework version is 5.2.31
- stormpath/laravel version is 0.4.0
- php version is 5.6.15

if you have  `STORMPATH_CLIENT_APIKEY_ID`, `STORMPATH_CLIENT_APIKEY_SECRET`, `STORMPATH_APPLICATION_HREF` in your `.env` file. You can see that exception.

![screen shot 2016-05-03 at 08 21 09](https://cloud.githubusercontent.com/assets/1067132/14975203/25516b7c-1108-11e6-8e0d-9000400f3137.png)

![screen shot 2016-05-03 at 08 21 49](https://cloud.githubusercontent.com/assets/1067132/14975206/2b20ad4c-1108-11e6-9ce7-21c54499a71f.png)

---

Also, when I remove `STORMPATH_CLIENT_APIKEY_ID`, `STORMPATH_CLIENT_APIKEY_SECRET`, `STORMPATH_APPLICATION_HREF` from my `.env` file.

`php artisan route:list` output : 

![screen shot 2016-05-03 at 10 24 41](https://cloud.githubusercontent.com/assets/1067132/14977050/9386ba82-1119-11e6-9307-fda0c3a2bd09.png)

But when `.env` file has `STORMPATH_CLIENT_APIKEY_ID`, `STORMPATH_CLIENT_APIKEY_SECRET`, `STORMPATH_APPLICATION_HREF`.

`php artisan route:list` output : 

![screen shot 2016-05-03 at 10 25 05](https://cloud.githubusercontent.com/assets/1067132/14977059/abd3c530-1119-11e6-995f-caa6c2643865.png)

---

When I use only stormpath/sdk without laravel project, I can connect stormpath and login successfuly.

```
{
    "require": {
        "stormpath/sdk": "1.14.*"
    }
}
```

```
<?php

require 'vendor/autoload.php';

\Stormpath\Client::$apiKeyFileLocation = $_SERVER['HOME'] . '/.stormpath/apiKey.properties';
$client = Stormpath\Client::getInstance();

$application = Stormpath\Resource\Application::get('https://api.stormpath.com/v1/applications/XXXXXX');


try {
  $result = $application->authenticate('User', 'Pass');
  $account = $result->account;

  echo "<pre>";
  print_r($account);
} catch (\Stormpath\Resource\ResourceError $e) {
  echo $e->getMessage();
}
```

**Comment by nurettintopal** [comment]
@bretterer 

I have resolved this issue this way:

stormpath-laravel/src/Support/StormpathLaravelServiceProvider.php

before:
`
    $accountStoreArray[] = [
        'href' => $mapping->accountStore->href,
        'name' => $mapping->accountStore->name,
        'provider' => [
            'href' => $mapping->accountStore->provider->href,
            'providerId' => $mapping->accountStore->provider->providerId,
        ]
    ];
`

after:
`$accountStoreArray[] = [
                'href' => $mapping->accountStore->href,
                'name' => $mapping->accountStore->name,
                'provider' => [
                  'href' => isset($mapping->accountStore->provider->href) ? $mapping->accountStore->provider->href : null,
                  'providerId' => isset($mapping->accountStore->provider->providerId) ? $mapping->accountStore->provider->providerId : null,
                ]
            ];`

Do you think that this is a correct way to resolve this issue? 

I have sent a pull request(https://github.com/stormpath/stormpath-laravel/pull/48). please review it.

**Comment by bretterer** [comment]
@nurettintopal please see comments on the PR.  I think what is happening here is that your application has something other than directories in the account store mappings.  I would guess groups or organizations.  This brought in a bug with the laravel integration.  We will need to get this resolved.

**Comment by nurettintopal** [comment]
@bretterer I updated my pull request. 

I set the accountStoreArray without provider and if the $mapping->accountStore->provider is exist, I attach it. 

I think it seems to be fine.
