### ISSUE TITLE
Can't get stormpath working on laravel 5.2

### ISSUE THREAD

**Issue by injective-edu** [stormpath/stormpath-laravel#53]
Problem 1
    - Installation request for stormpath/laravel ^0.4.1 -> satisfiable by stormpath/laravel[0.4.1].
    - Conclusion: remove symfony/event-dispatcher v3.1.3
    - Conclusion: don't install symfony/event-dispatcher v3.1.3
    - stormpath/laravel 0.4.1 requires stormpath/sdk ~1.14 -> satisfiable by stormpath/sdk[1.14.0, 1.15.0, 1.16.0].
    - stormpath/sdk 1.14.0 requires guzzle/guzzle 3.9.\* -> satisfiable by guzzle/guzzle[v3.9.0, v3.9.1, v3.9.2, v3.9.3].
    - stormpath/sdk 1.15.0 requires guzzle/guzzle 3.9.\* -> satisfiable by guzzle/guzzle[v3.9.0, v3.9.1, v3.9.2, v3.9.3].
    - stormpath/sdk 1.16.0 requires guzzle/guzzle 3.9.\* -> satisfiable by guzzle/guzzle[v3.9.0, v3.9.1, v3.9.2, v3.9.3].
    - guzzle/guzzle v3.9.0 requires symfony/event-dispatcher ~2.1 -> satisfiable by symfony/event-dispatcher[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - guzzle/guzzle v3.9.1 requires symfony/event-dispatcher ~2.1 -> satisfiable by symfony/event-dispatcher[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - guzzle/guzzle v3.9.2 requires symfony/event-dispatcher ~2.1 -> satisfiable by symfony/event-dispatcher[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - guzzle/guzzle v3.9.3 requires symfony/event-dispatcher ~2.1 -> satisfiable by symfony/event-dispatcher[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - Can only install one of: symfony/event-dispatcher[v2.8.0, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.1, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.2, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.3, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.4, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.5, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.6, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.7, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.8, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.8.9, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.1.0, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.1.1, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.1.10, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.1.11, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.1.12, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.1.13, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.1.2, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.1.3, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.1.4, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.1.5, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.1.6, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.1.7, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.1.8, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.1.9, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.2.0, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.2.1, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.2.10, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.2.11, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.2.2, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.2.3, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.2.4, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.2.5, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.2.6, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.2.7, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.2.8, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.2.9, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.0, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.1, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.10, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.11, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.12, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.13, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.14, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.15, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.16, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.17, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.18, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.19, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.2, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.20, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.21, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.22, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.23, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.24, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.25, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.26, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.27, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.28, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.29, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.3, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.30, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.31, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.32, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.33, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.34, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.35, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.36, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.37, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.38, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.39, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.4, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.40, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.41, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.42, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.5, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.6, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.7, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.8, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.3.9, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.4.0, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.4.1, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.4.10, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.4.2, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.4.3, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.4.4, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.4.5, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.4.6, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.4.7, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.4.8, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.4.9, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.5.0, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.5.1, v3.1.3].
    - Can only install one of: symfony/event-dispatcher[v2.5.10, v3.1.3].

**Comment by injective-edu** [comment]
I run "composer require  stormpath/laravel --update-with-dependencies"

**Comment by injective-edu** [comment]
Solved! I re-put the require in the composer.json then run composer update

**Comment by bretterer** [comment]
Hi Injective-edu.  Thank you for coming in to report this.  It is a known issue at the moment and should be fixed in the near future when we update guzzle package on the stormpath-sdk.  Read more at #17
