### ISSUE TITLE
Undefined variable: areaWrap

### ISSUE THREAD

**Issue by chaseconey** [stormpath/stormpath-laravel#58]
Doing the default installation of this package yields to this error:

```
Undefined variable: areaWrap (View: /projects/oauth-stormpath/vendor/stormpath/laravel/src/views/login.blade.php)
```

It seems it is referencing a variable at the top of the file that is commented out.

Current version of the package: `0.4.2`

**Comment by xRahul** [comment]
Looking into it, but I could do with some help @bretterer

**Comment by imam** [comment]
+1
