### ISSUE TITLE
Stormpath prohibits Laravel Passport from installing

### ISSUE THREAD

**Issue by markuskoehler** [stormpath/stormpath-laravel#64]
On Laravel 5.3, after installing Stormpath-Laravel, one is not able to install Laravel Passport. The issue is the version of firebase/php-jwt which both require. Stormpath loads v2.2.0 of JWT, Passport requires v4.

Would it be possible to upgrade JWT on Stormpath-Laravel to at least v4 to remove this blocking behaviour?

**Comment by bretterer** [comment]
Thank you for the bug report on this.  I will put it on the agenda to update the JWT library for the core SDK 

-Brian

**Comment by bretterer** [comment]
Released new version to fix this.  Version 0.5.1 uses the new Firebase\JWT\JWT namespace and the https://github.com/stormpath/stormpath-sdk-php/releases/tag/1.17.2 release of the core php sdk updates the package.
