### ISSUE TITLE
Error ReflectionException

### ISSUE THREAD

**Issue by UlisesCarreon** [stormpath/stormpath-laravel#67]
![captura de pantalla 2017-01-27 a la s 11 08 07](https://cloud.githubusercontent.com/assets/4529504/22379912/fb1e488c-e480-11e6-9a05-275e835f97cd.png)

I follow all the steps, but i'm getting this error.

Any advice?

**Comment by bretterer** [comment]
Currently, this integration only works for Laravel 5.2 and 5.3.

It is on the road map to update, but no timeline has been set yet.
