### ISSUE TITLE
Get user_id

### ISSUE THREAD

**Issue by yawuar** [stormpath/stormpath-laravel#68]
Hi!

Is it possible to get the users id? I tried with the app function  | app('stormpath.user')->id | but without succes.

Does anyone know how to do this?

Thanks!

**Comment by bretterer** [comment]
Hi @yawuar,

Can you try `app('stormpath.user')->getId()`

**Comment by yawuar** [comment]
No, that doesn't work.

**Comment by bretterer** [comment]
I'm sorry,  This call is actually `->href` as that is what is used for ID.  We never implemented an ID method as an alias for the user.

**Comment by yawuar** [comment]
@bretterer 

Awesome, it works!

Thanks!

**Comment by bretterer** [comment]
Glad to hear it!
